#!/bin/bash 

#automatically compile java files and perform tests on the given week directory

export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"
export PATH=$JAVA_HOME/bin:$PATH

for w in $@ 
do 
(
    cd ${w} || exit
    for java_files in $(ls -f *.java) 
    do
    class_file=${java_files%.*}.class
    if [ -f "$class_file" ]; then
        echo "$class_file exists."
    else
        javac -cp .:../stdlib.jar ${java_files}
    fi
  
done
./test   
)

done
