#!/bin/bash

set JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/"
export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/"
export PATH=$JAVA_HOME/bin:$PATH

cd ${0%/*} || exit 1    # Run from this directory
assignment="Week4"

(cd ${assignment} &&  zip -j  submit.zip $(ls -f *.java))
