#!/bin/bash

# java -cp .:../stdlib.jar ActivationFunction 0.0
# echo "----"
# java -cp .:../stdlib.jar ActivationFunction 1.0
# echo "----"
# java -cp .:../stdlib.jar ActivationFunction -0.5

java -cp .:../stdlib.jar PlayThatNote 440.0 3.0
java -cp .:../stdlib.jar PlayThatNote  880.0  3.0

#java -cp .:../stdlib.jar Divisors 987 610
